name: Brakeman Scan
on:
  - push
jobs:
  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Brakeman Run
        continue-on-error: true
        run: bundle exec brakeman -7 -A -z -q --ensure-latest
