name: brakeman
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: brakeman
        run: bundle exec brakeman -7 -A -z -q --ensure-latest
