name: BundlerAudit Scan
on:
  - push
jobs:
  bundler-audit-scan:
    name: BundlerAudit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Setup BundlerAudit
        run: gem install bundler-audit

      - name: BundlerAudit Run
        continue-on-error: true
        run: bundler-audit check --update
