name: bundler-audit
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: bundler-audit
        run: bundle exec bundler-audit update && bundler-audit
